FROM golang:1.21-alpine3.19 AS builder

RUN go version

COPY ./ /CRUD_API

WORKDIR /CRUD_API

RUN go mod download && go get -u ./...
RUN go build -o crud_api ./cmd/main.go

EXPOSE 80

CMD ["./crud_api"]
