name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: "crud-api"
  CONTAINER_NAME: "crud_api"
  ENV_FILE_PATH: "./crud-api/.env.prod"
  LOGS_PATH: "/root/crud-api/api/logs/prod"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Test
        run: go test ./...

#нам нужно облако развертывания приложения ,тк оно нам создаet эндпоинт для нашего приложения, который будет доступен в интернете.После развертывания ,я получаю URL-адресс приложения


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Deploy locally
        uses: actions/checkout@v2
      - name: Deploy to Remote Server
        run: |
            # Stop running container
            docker stop $(echo $CONTAINER_NAME) || true

            # Remove old container
            docker rm $(echo $CONTAINER_NAME) || true

            # Run a new container from a new image
            docker run --name $(echo $CONTAINER_NAME) \
            -e POSTGRES_PASSWORD=qwerty \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_DB=postgres \
            -e POSTGRES_HOST=localhost \
            -p 5432:5432 \

         sleep 31s
          
         docker exec -it $(echo $CONTAINER_NAME) migrate -path ./schema -database "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable" up
        



